CREATE TABLE `wpag_term_taxonomy` (  `term_taxonomy_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `term_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `taxonomy` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',  `description` longtext COLLATE utf8mb4_unicode_ci NOT NULL,  `parent` bigint(20) unsigned NOT NULL DEFAULT '0',  `count` bigint(20) NOT NULL DEFAULT '0',  PRIMARY KEY (`term_taxonomy_id`),  UNIQUE KEY `term_id_taxonomy` (`term_id`,`taxonomy`),  KEY `taxonomy` (`taxonomy`)) ENGINE=MyISAM AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `wpag_term_taxonomy` DISABLE KEYS */;
INSERT INTO `wpag_term_taxonomy` VALUES('1', '1', 'category', '', '0', '0');
INSERT INTO `wpag_term_taxonomy` VALUES('2', '2', 'post_format', '', '0', '0');
INSERT INTO `wpag_term_taxonomy` VALUES('3', '3', 'nav_menu', '', '0', '6');
INSERT INTO `wpag_term_taxonomy` VALUES('4', '4', 'nav_menu', '', '0', '0');
INSERT INTO `wpag_term_taxonomy` VALUES('5', '5', 'post_tag', '', '0', '4');
INSERT INTO `wpag_term_taxonomy` VALUES('6', '6', 'post_tag', '', '0', '1');
INSERT INTO `wpag_term_taxonomy` VALUES('7', '7', 'post_tag', '', '0', '3');
INSERT INTO `wpag_term_taxonomy` VALUES('8', '8', 'post_tag', '', '0', '3');
INSERT INTO `wpag_term_taxonomy` VALUES('9', '9', 'post_tag', '', '0', '4');
INSERT INTO `wpag_term_taxonomy` VALUES('10', '10', 'post_tag', '', '0', '3');
INSERT INTO `wpag_term_taxonomy` VALUES('11', '11', 'post_tag', '', '0', '3');
INSERT INTO `wpag_term_taxonomy` VALUES('12', '12', 'category', '', '0', '0');
INSERT INTO `wpag_term_taxonomy` VALUES('13', '13', 'category', '', '12', '0');
INSERT INTO `wpag_term_taxonomy` VALUES('14', '14', 'category', '', '0', '4');
INSERT INTO `wpag_term_taxonomy` VALUES('15', '15', 'post_tag', '', '0', '3');
INSERT INTO `wpag_term_taxonomy` VALUES('16', '16', 'post_tag', '', '0', '2');
/*!40000 ALTER TABLE `wpag_term_taxonomy` ENABLE KEYS */;
