CREATE TABLE `wpag_terms` (  `term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',  `slug` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',  `term_group` bigint(10) NOT NULL DEFAULT '0',  PRIMARY KEY (`term_id`),  KEY `slug` (`slug`(191)),  KEY `name` (`name`(191))) ENGINE=MyISAM AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `wpag_terms` DISABLE KEYS */;
INSERT INTO `wpag_terms` VALUES('1', 'Uncategorized', 'uncategorized', '0');
INSERT INTO `wpag_terms` VALUES('2', 'post-format-audio', 'post-format-audio', '0');
INSERT INTO `wpag_terms` VALUES('3', 'Main Menu', 'main-menu', '0');
INSERT INTO `wpag_terms` VALUES('4', 'Footer', 'footer', '0');
INSERT INTO `wpag_terms` VALUES('5', 'AgilData', 'agildata', '0');
INSERT INTO `wpag_terms` VALUES('6', 'CEO', 'ceo', '0');
INSERT INTO `wpag_terms` VALUES('7', 'Streaming Thought Leaders', 'streaming-thought-leaders', '0');
INSERT INTO `wpag_terms` VALUES('8', 'Big Data', 'big-data', '0');
INSERT INTO `wpag_terms` VALUES('9', 'Stream Processing', 'stream-processing', '0');
INSERT INTO `wpag_terms` VALUES('10', 'Big Data Leader', 'big-data-leader', '0');
INSERT INTO `wpag_terms` VALUES('11', 'Big Data Database', 'big-data-database', '0');
INSERT INTO `wpag_terms` VALUES('12', 'Engineering', 'engineering', '0');
INSERT INTO `wpag_terms` VALUES('13', 'Tips and Tricks', 'tips-and-tricks', '0');
INSERT INTO `wpag_terms` VALUES('14', 'AgilData News', 'agildata-news', '0');
INSERT INTO `wpag_terms` VALUES('15', 'agile big data', 'agile-big-data', '0');
INSERT INTO `wpag_terms` VALUES('16', 'Cloud Expo West', 'cloud-expo-west', '0');
/*!40000 ALTER TABLE `wpag_terms` ENABLE KEYS */;
